/* CutterControl.h
 * MSG file auto generated by "Rutgers avr_bridge"
 */
#ifndef CUTTERCONTROL_H_
#define CUTTERCONTROL_H_
#include "avr_ros/Msg.h"
#include "avr_ros/vector.h"
#include "avr_ros/ros_string.h"
namespace avr_bridge {
	class CutterControl : public ros::Msg {
	public:
		ros::MsgSz bytes();
		ros::MsgSz serialize(uint8_t *out_buffer);
		ros::MsgSz deserialize(uint8_t *data);
		bool LeftControl;
		bool RightControl;
	}; /* class CutterControl */
} /* namespace avr_bridge */
#endif /* CUTTERCONTROL_H_ */
