/* PowerControl.h
 * MSG file auto generated by "Rutgers avr_bridge"
 */
#ifndef POWERCONTROL_H_
#define POWERCONTROL_H_
#include "avr_ros/Msg.h"
#include "avr_ros/vector.h"
#include "avr_ros/ros_string.h"
namespace avr_bridge {
	class PowerControl : public ros::Msg {
	public:
		ros::MsgSz bytes();
		ros::MsgSz serialize(uint8_t *out_buffer);
		ros::MsgSz deserialize(uint8_t *data);
		float Voltage;
		float Current;
		float StateofCharge;
		float Temperature1;
		float Temperature2;
		bool LeftCutterStatus;
		bool RightCutterStatus;
	}; /* class PowerControl */
} /* namespace avr_bridge */
#endif /* POWERCONTROL_H_ */
